### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by 01Space** [plainFlight/plainFlightController#2]
Hello! Your code is fantastic! I tried to compile the code and found that the ARDUINO IDE prompted that it could not be compiled.

C:\Users\86186\Downloads\plainFlightController-1.0.0\PlainFlightController\Actuators.ino: In function 'void initActuators()':
Actuators:55:7: error: 'ledcSetup' was not declared in this scope
   55 |       ledcSetup(i, SERVO_REFRESH, LEDC_RESOLUTION);
      |       ^~~~~~~~~
Actuators:56:7: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
   56 |       ledcAttachPin(pwmPin[i], i);
      |       ^~~~~~~~~~~~~
      |       ledcAttach
Actuators:74:9: error: 'ledcSetup' was not declared in this scope
   74 |         ledcSetup(i, SERVO_REFRESH, LEDC_RESOLUTION);
      |         ^~~~~~~~~
Actuators:75:9: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
   75 |         ledcAttachPin(pwmPin[i], i);
      |         ^~~~~~~~~~~~~
      |         ledcAttach

**Comment by plainFlight** [comment]
Sounds like you have not downloaded/installed the ESP32 Espressif library... see the instructions for what libraries are needed. The functions Arduino is complaining about are part of that library.

**Comment by 01Space** [comment]
Thank you! I have resolved the compilation issue. The problem is that I am using Espressif Systems ESP32 (3.0.0-RC3) and can compile using an older version (2.0.14)
Can you share the 3D printing design files and ARDUINO source code of BiCopter/DualCopter? Many people are very interested in your BiCopter/DualCopter project! Do you use Discord server? You can establish a Discord server for PlainFlightController, so that anyone interested in PlainFlightController can join the Discord server for communication or discussion.
